from __future__ import annotations

from .common import ConversionDiagnostic, ConversionResult, namespace_name, sanitize_identifier


class EquivalenceSkeletonGenerator:
    """Generate a Lean4 obligation connecting MATLAB and HDL source models."""

    def generate(self, design_name: str, has_matlab: bool, has_hdl: bool) -> ConversionResult:
        name = sanitize_identifier(design_name or "design")
        ns = namespace_name("QEDSoft_Equivalence", name)
        diagnostics: list[ConversionDiagnostic] = []
        if not (has_matlab and has_hdl):
            diagnostics.append(
                ConversionDiagnostic(
                    "equivalence",
                    "warning",
                    "Equivalence proof skeleton is informative because both MATLAB and HDL models were not provided.",
                )
            )

        lean = "\n".join(
            [
                "-- Auto-generated by QEDSoft Job 2: QEDAI equivalence-verifier entry point.",
                "-- Replace this scaffold with imported MATLAB/HDL step relations as the converters mature.",
                f"namespace {ns}",
                "",
                "structure EquivalenceObligation where",
                "  matlab_model_available : Bool",
                "  hdl_model_available : Bool",
                "",
                "def obligation : EquivalenceObligation :=",
                f"  {{ matlab_model_available := {str(has_matlab).lower()},",
                f"    hdl_model_available := {str(has_hdl).lower()} }}",
                "",
                "theorem qedai_verifier_entrypoint :",
                "    obligation.matlab_model_available = true ->",
                "    obligation.hdl_model_available = true ->",
                "    True := by",
                "  intro _hmatlab _hhdl",
                "  trivial",
                "",
                f"end {ns}",
                "",
            ]
        )
        return ConversionResult(
            "equivalence",
            name,
            lean,
            diagnostics,
            {
                "has_matlab": has_matlab,
                "has_hdl": has_hdl,
                "is_proof_scaffold": True,
            },
        )
