from __future__ import annotations

import re

from qedsoft.models import FormalizationBundle


class LeanContractGenerator:
    """Generate a Lean4 contract skeleton for chip verification obligations.

    The generated file is intentionally self-contained and compilable without a
    custom hardware DSL. Teams can later replace the placeholder predicates with
    a richer Lean HDL or circuit semantics.
    """

    def generate(self, bundle: FormalizationBundle) -> str:
        model = bundle.model
        lines: list[str] = [
            "-- Auto-generated by QEDSoft.",
            "-- This Lean contract mirrors the generated SVA obligations.",
            "",
            f"namespace QEDSoft_{self._safe_name(model.top_module)}",
            "",
            "structure State where",
        ]

        state_signals = [
            signal
            for signal in model.signals.values()
            if signal.name not in {model.clock, model.reset}
        ]
        if not state_signals:
            lines.append("  dummy : Bool")
        else:
            for signal in state_signals:
                lean_type = "Bool" if signal.width <= 1 else "Nat"
                lines.append(f"  {self._safe_name(signal.name)} : {lean_type}")

        lines.extend(
            [
                "",
                "abbrev Trace := Nat -> State",
                "",
                "-- Replace these predicates with precise transition semantics as the model matures.",
                "def valid_inputs (_t : Trace) : Prop := True",
                "def rtl_transition (_prev _next : State) : Prop := True",
                "",
            ]
        )

        if not bundle.subgoals:
            lines.extend(["theorem qedsoft_no_requirements : True := by", "  trivial", ""])
        else:
            req_by_id = {req.id: req for req in model.requirements}
            for subgoal in bundle.subgoals:
                req = req_by_id.get(subgoal.requirement_id)
                category = req.category if req else "functional"
                statement = req.text if req else subgoal.statement
                theorem_name = self._safe_name(f"{subgoal.id}_{category}").lower()
                lines.extend(
                    [
                        f"-- Requirement {subgoal.requirement_id}: {self._comment(statement)}",
                        f"def {theorem_name}_property (_t : Trace) : Prop := True",
                        f"theorem {theorem_name}_holds (t : Trace) :",
                        f"    valid_inputs t -> {theorem_name}_property t := by",
                        "  intro _hvalid",
                        "  trivial",
                        "",
                    ]
                )

        lines.append(f"end QEDSoft_{self._safe_name(model.top_module)}")
        lines.append("")
        return "\n".join(lines)

    def _safe_name(self, value: str) -> str:
        name = re.sub(r"[^A-Za-z0-9_]", "_", value)
        if name and name[0].isdigit():
            name = f"n_{name}"
        return name or "unnamed"

    def _comment(self, value: str) -> str:
        cleaned = re.sub(r"\s+", " ", value).strip()
        return cleaned[:150]
