from __future__ import annotations

import re

from qedsoft.models import DesignModel, FormalizationBundle, Requirement, VerificationSubgoal


class SVAGenerator:
    """Generate SystemVerilog Assertions from QEDSoft subgoals."""

    def generate(self, bundle: FormalizationBundle) -> tuple[str, str]:
        model = bundle.model
        port_lines = self._port_lines(model)
        property_blocks: list[str] = []

        req_by_id = {requirement.id: requirement for requirement in model.requirements}
        for subgoal in sorted(bundle.subgoals, key=lambda item: (-item.priority, item.id)):
            requirement = req_by_id.get(subgoal.requirement_id)
            if requirement is None:
                continue
            property_blocks.append(self._property_for_requirement(model, subgoal, requirement))

        if not property_blocks:
            property_blocks.append(self._placeholder_property(model))

        module_name = f"{model.top_module}_qedsoft_sva"
        sva = "\n".join(
            [
                "// Auto-generated by QEDSoft.",
                "// Review low-confidence properties before signoff.",
                "`default_nettype none",
                f"module {module_name} #(",
                "  parameter int DEPTH = 16",
                ") (",
                port_lines,
                ");",
                "",
                f"  default clocking qedsoft_cb @(posedge {model.clock}); endclocking",
                "",
                *property_blocks,
                "endmodule",
                "`default_nettype wire",
                "",
            ]
        )
        bind = self.generate_bind(model, module_name)
        return sva, bind

    def generate_bind(self, model: DesignModel, assertion_module_name: str | None = None) -> str:
        assertion_module_name = assertion_module_name or f"{model.top_module}_qedsoft_sva"
        return "\n".join(
            [
                "// Bind file generated by QEDSoft.",
                "// Compile this file with the RTL and assertion module.",
                f"bind {model.top_module} {assertion_module_name} #(.DEPTH(DEPTH)) qedsoft_sva_i (.*);",
                "",
            ]
        )

    def _port_lines(self, model: DesignModel) -> str:
        ports = []
        for signal in model.signals.values():
            if signal.direction not in {"input", "output", "inout"}:
                continue
            width = "" if signal.width <= 1 else f" [{signal.width - 1}:0]"
            direction = "input" if signal.direction == "output" else signal.direction
            ports.append(f"  {direction} logic{width} {signal.name}")

        if model.clock not in model.signals:
            ports.insert(0, f"  input logic {model.clock}")
        if model.reset not in model.signals:
            ports.insert(1, f"  input logic {model.reset}")

        return ",\n".join(ports)

    def _property_for_requirement(
        self, model: DesignModel, subgoal: VerificationSubgoal, requirement: Requirement
    ) -> str:
        name = self._safe_name(f"qedsoft_{requirement.id.lower()}_{requirement.category}")
        expr, confidence_note = self._expression_for_requirement(model, requirement)
        disable = self._disable_iff(model)
        comment = self._comment(requirement.text, subgoal.confidence, confidence_note)

        if requirement.category == "reset":
            antecedent = self._reset_condition(model)
            body = f"{antecedent} |=> ({expr})"
        else:
            body = f"{disable} ({expr})"

        return "\n".join(
            [
                comment,
                f"  property {name};",
                f"    {body};",
                "  endproperty",
                f"  assert property ({name}) else $error(\"QEDSoft violation: {requirement.id}\");",
                "",
            ]
        )

    def _expression_for_requirement(self, model: DesignModel, requirement: Requirement) -> tuple[str, str]:
        text = requirement.text.lower()
        signals = set(model.signals)

        reset_expr = self._parse_reset_value(requirement.text, signals)
        if requirement.category == "reset" and reset_expr:
            return reset_expr, "template: reset-value"

        counter_expr = self._parse_counter_relation(requirement.text, signals)
        if counter_expr:
            return counter_expr, "template: counter-relation"

        guard_expr = self._parse_never_guard(requirement.text, signals)
        if guard_expr:
            return guard_expr, "template: safety-guard"

        handshake_expr = self._parse_handshake(requirement.text, signals, requirement.latency_cycles)
        if handshake_expr:
            return handshake_expr, "template: bounded-response"

        stable_expr = self._parse_stability(requirement.text, signals)
        if stable_expr:
            return stable_expr, "template: stability"

        if "must be zero" in text or "shall be zero" in text:
            target = requirement.signals[0] if requirement.signals else self._first_data_signal(model)
            return f"{target} == '0", "template: zero-value"

        if requirement.signals:
            return f"!$isunknown({requirement.signals[0]})", "fallback: known-value"

        return "1'b1", "fallback: manual-review-required"

    def _parse_reset_value(self, text: str, signals: set[str]) -> str | None:
        lowered = text.lower()
        for signal in signals:
            if signal.lower() not in lowered:
                continue
            if re.search(rf"\b{re.escape(signal.lower())}\b.*\b(zero|0)\b", lowered):
                return f"{signal} == '0"
            one_match = re.search(rf"\b{re.escape(signal.lower())}\b.*\b(one|1)\b", lowered)
            if one_match:
                return f"{signal} == 1'b1"
        return None

    def _parse_never_guard(self, text: str, signals: set[str]) -> str | None:
        lowered = text.lower()
        pairs = [
            ("read", "rd", "empty"),
            ("rd", "rd", "empty"),
            ("write", "wr", "full"),
            ("wr", "wr", "full"),
            ("overflow", "wr", "full"),
            ("underflow", "rd", "empty"),
        ]
        for text_hint, signal_hint, state_hint in pairs:
            action = self._find_signal_by_hint(signals, text_hint) or self._find_signal_by_hint(signals, signal_hint)
            state = self._find_signal_by_hint(signals, state_hint)
            if action and state and text_hint in lowered and state_hint in lowered:
                return f"{action} |-> !{state}"

        if "never" in lowered and len(signals) >= 2:
            mentioned = [signal for signal in signals if signal.lower() in lowered]
            if len(mentioned) >= 2:
                return f"{mentioned[0]} |-> !{mentioned[1]}"
        return None

    def _parse_counter_relation(self, text: str, signals: set[str]) -> str | None:
        lowered = text.lower()
        count = self._find_signal_by_hint(signals, "count")
        empty = self._find_signal_by_hint(signals, "empty")
        full = self._find_signal_by_hint(signals, "full")
        wr = self._find_signal_by_hint(signals, "wr") or self._find_signal_by_hint(signals, "write")
        rd = self._find_signal_by_hint(signals, "rd") or self._find_signal_by_hint(signals, "read")

        if count and empty and "empty" in lowered and ("zero" in lowered or "0" in lowered):
            return f"({count} == '0) |-> {empty}"
        if count and full and "full" in lowered and ("depth" in lowered or "maximum" in lowered):
            return f"({count} == DEPTH) |-> {full}"
        if count and wr and "increase" in lowered:
            guard = f"{wr}"
            if full:
                guard += f" && !{full}"
            return f"({guard}) |=> {count} == $past({count}) + 1'b1"
        if count and rd and "decrease" in lowered:
            guard = f"{rd}"
            if empty:
                guard += f" && !{empty}"
            return f"({guard}) |=> {count} == $past({count}) - 1'b1"
        return None

    def _parse_handshake(self, text: str, signals: set[str], latency: int | None) -> str | None:
        lowered = text.lower()
        req = self._find_signal_by_hint(signals, "req") or self._find_signal_by_hint(signals, "valid")
        ack = self._find_signal_by_hint(signals, "ack") or self._find_signal_by_hint(signals, "ready")
        if not req or not ack:
            return None
        if not any(word in lowered for word in ["within", "after", "follow", "eventually", "ready", "ack"]):
            return None
        max_latency = latency or 1
        return f"$rose({req}) |-> ##[1:{max_latency}] {ack}"

    def _parse_stability(self, text: str, signals: set[str]) -> str | None:
        lowered = text.lower()
        if "stable" not in lowered:
            return None
        mentioned = [signal for signal in signals if signal.lower() in lowered]
        if not mentioned:
            return None
        return f"{mentioned[0]} |-> $stable({mentioned[0]})"

    def _find_signal_by_hint(self, signals: set[str], hint: str) -> str | None:
        for signal in sorted(signals):
            if hint in signal.lower():
                return signal
        return None

    def _disable_iff(self, model: DesignModel) -> str:
        reset_cond = f"!{model.reset}" if model.reset_active_low else model.reset
        return f"disable iff ({reset_cond})"

    def _reset_condition(self, model: DesignModel) -> str:
        return f"!{model.reset}" if model.reset_active_low else model.reset

    def _first_data_signal(self, model: DesignModel) -> str:
        for signal in model.signals.values():
            if signal.name not in {model.clock, model.reset}:
                return signal.name
        return model.reset

    def _placeholder_property(self, model: DesignModel) -> str:
        return "\n".join(
            [
                "  // No concrete requirements were extracted. This cover keeps the flow runnable.",
                "  property qedsoft_no_requirements_extracted;",
                f"    disable iff ({self._reset_condition(model)}) 1'b1;",
                "  endproperty",
                "  cover property (qedsoft_no_requirements_extracted);",
                "",
            ]
        )

    def _comment(self, text: str, confidence: float, note: str) -> str:
        cleaned = re.sub(r"\s+", " ", text).strip()
        if len(cleaned) > 120:
            cleaned = cleaned[:117] + "..."
        return "\n".join(
            [
                f"  // Requirement: {cleaned}",
                f"  // Confidence: {confidence:.2f}; {note}",
            ]
        )

    def _safe_name(self, value: str) -> str:
        return re.sub(r"[^A-Za-z0-9_]", "_", value).replace("-", "_")
